name: Publish (wasm)

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_RELEASE_LTO: 'fat'
  CI: '1'

on:
  create:
    tags:
      - v*

jobs:
  publish-node:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    name: Build - wasm for node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            **/target/
          key: ${{ runner.os }}-publish-integration

      - name: Install node dependencies
        run: |
          echo "@odenlang:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          yarn

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        working-directory: crates/binding_core_wasm
        run: |
          wasm-pack build --out-name wasm --release --scope=swc --target nodejs
          sed -i -e 's/"name": "@swc\/binding_core_wasm"/"name": "@odenlang\/swc-wasm-test"/g' pkg/package.json
          sed -i -e 's/swc-project/odenlang/g' pkg/package.json

      - name: Publish
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          (cd crates/binding_core_wasm/pkg && npm publish --access public --registry https://npm.pkg.github.com/)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-web:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    name: Build - wasm for web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            **/target/
          key: ${{ runner.os }}-publish-integration

      - name: Install node dependencies
        run: |
          echo "@odenlang:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          yarn

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        working-directory: crates/binding_core_wasm
        run: |
          wasm-pack build --out-name wasm-web --release --scope=swc --target web
          sed -i -e 's/"name": "@swc\/binding_core_wasm"/"name": "@odenlang\/swc-wasm-web-test"/g' pkg/package.json
          sed -i -e 's/swc-project/odenlang/g' pkg/package.json

      - name: Publish
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          (cd crates/binding_core_wasm/pkg && npm publish --access public --registry https://npm.pkg.github.com/)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
