name: Windows Yarn Test

on:
  pull_request:

jobs:
  gogogo:
    name: Testing
    runs-on: windows-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: odenlang
          check-latest: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          yarn init -y
          yarn add @odenlang/swc-core-win32-x64-msvc
